services:
  my-app:
    build: ./api
    depends_on:
      - mongodb-database
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb-database:27017/mongodb
      - DB_NAME=mongodb-database
  mongodb-database:
    restart: always
    image: mongo:latest
    volumes: 
      - mydatabase:/data/db
volumes:
  mydatabase:
