services:
  mongodb-app:
    container_name: mongodb-app
    build: ./api
    depends_on:
      - mongodb-database
    networks:
      - mongodb-network
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - HOST=${HOST}
      - DB_NAME=${DB_NAME}

  mongodb-database:
    container_name: mongodb-database
    restart: always
    networks:
      - mongodb-network
    image: mongo:latest
    volumes: 
      - ./mydata:/data/db

networks:
  mongodb-network:
    driver: bridge
