services:
  my-app:
    build: ./api
    depends_on:
      - mongodb-database
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
  mongodb-database:
    restart: always
    image: mongo:latest
    volumes: 
      - mydatabase:/data/db
volumes:
  mydatabase:
