services:
  mongodb-app:
    container_name: mongodb-app
    build: .
    depends_on:
      - mongodb-database
    networks:
      - mongodb-network
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongodb-database:27017/mongodb
      - HOST=mongodb-database
      - DB_NAME=mongodb-database

  mongodb-database:
    container_name: mongodb-database
    networks:
      - mongodb-network
    image: mongo:latest
    volumes: 
      - ./mydata:/data/db

networks:
  mongodb-network:
    driver: bridge
