services:
  mongodb-app:
    build: ./api
    depends_on:
      - mongodb-database
    ports:
      - "80:3000"
    environment:
      - PORT=3000
      - MONGO_URL=${MONGO_URL}
      # - HOST=${HOST}
      - DB_NAME=${DB_NAME}

  mongodb-database:
    restart: always
    image: mongo:latest
    volumes: 
      - ./mydata:/data/db

networks:
  mongodb-network:
    driver: bridge
